name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash

jobs:
  build-and-run-examples:
    runs-on: ubuntu-18.04
    container: teaclave/teaclave-trustzone-sdk-build:0.1.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Building
        run: |
          make optee &&
          source environment &&
          rustup default nightly-2019-07-08 &&
          (cd optee-utee && xargo build --target aarch64-unknown-optee-trustzone -vv) &&
          (cd optee-teec && cargo build --target aarch64-unknown-linux-gnu -vv)
          make examples
      - name: Run tests and examples
        run: |
          cd ci && ./ci.sh
